### ISSUE TITLE
Error: "Couldn't read NPC_22"

### ISSUE THREAD

**Issue by emsix** [mrkite/TerraFirma#100]
Hi,
I run into an error when switching on the texture option. I have the GOG version 1.4.0.4.
<img width="166" alt="error npc_22" src="https://user-images.githubusercontent.com/58268056/83619262-eccb3900-a58b-11ea-96b7-c7800a92b306.PNG">

**Comment by Faiakes** [comment]
Works for me. Steam version.

**Comment by mrkite** [comment]
Make sure the path to the textures is set correctly in Settings.  Its complaining that it cant find an .xnb, and NPC_22.xnb should definitely be in terraria's Content/Images folder.
