### ISSUE TITLE
Floating Tube?

### ISSUE THREAD

**Issue by Faiakes** [mrkite/TerraFirma#102]
Is this meant to be the: _Inner Tube_ ?

https://terraria.gamepedia.com/Inner_Tube

There is no reference to a Floating Tube on the official wiki.

**Comment by mrkite** [comment]
Yeah, that's the Inner Tube.  FloatingTube is the internal name for it.  If you go to Settings and set the correct path to Terraria.exe and select your language from the drop down, it'll use Terraria's translations.

**Comment by Faiakes** [comment]
Got it, thanks.
