### ISSUE TITLE
v.3.1.1 Linux not showing full map

### ISSUE THREAD

**Issue by freshoutdabox** [mrkite/TerraFirma#105]
TerraFirma doesn't show full map for worlds made before 1.4.0.5 but does show full map for worlds made in 1.4.0.5 normally. I'm not sure if this is a linux exclusive problem.

Examples are [This](https://cdn.discordapp.com/attachments/593142566627835906/718625634737193020/unknown.png) and [This](https://cdn.discordapp.com/attachments/593142566627835906/718628144856301598/unknown.png)

**Comment by mrkite** [comment]
I'm not sure what you mean by full map.  You can't zoom out further in linux?

**Comment by freshoutdabox** [comment]
It doesn't show all the tiles, the ones that aren't shown are replaced by "Murky Blackness".

**Comment by mrkite** [comment]
That's the Fog of War.  Turn that off in the view menu.  By default it's turned on and you can't see anything that your player hasn't seen in the game (you can also switch which player's fog of war to use in that same menu).  Turn it off and it shows everything.  It'll remember that you turned it off as well.

**Comment by freshoutdabox** [comment]
Ah thank you.
