### ISSUE TITLE
Is Russian localization needed?

### ISSUE THREAD

**Issue by nikitamatrosoff** [mrkite/TerraFirma#106]
I can translate the whole program to Russian and probably find people to translate it into other languages. Is it needed?

**Comment by nikitamatrosoff** [comment]
I'm experiencing the issue #104 also. The program doesn't start from console and no exit code is shown. Instructions from the help link there didn't help.

**Comment by nikitamatrosoff** [comment]
Update: looks like this issue is happening with earlier releases as well. Tried:
- 3.1.1
- 3.1
 - 3.0.19
- 3.0.18

**Comment by mrkite** [comment]
Could be your 3d drivers failing to load, although that usually just ends up with a blank window, not no window at all.

**Comment by nikitamatrosoff** [comment]
Here is no window at all. Maybe there are problems with libraries? I don't have Qt installed if it matters.

**Comment by mrkite** [comment]
It's a static compile.. there are no libraries needed.

**Comment by TheRealSaiph** [comment]
I'm using Terrafirma 3.1.1 on a UK PC under Win 10, and the program seems to run with no problem (once I located my textures directory), except for one thing. Mousing over a lot of the textures on the map shows the texture name in what appears to be Russian. Maybe the Russian localisation has gone a **bit** too far?  **;-)**

**Comment by nikitamatrosoff** [comment]
Created #107, check it!

**Comment by mrkite** [comment]
thanks!
