### ISSUE TITLE
Update for 1.4.1

### ISSUE THREAD

**Issue by mwalimu59** [mrkite/TerraFirma#111]
Terrafirma cannot open worlds if they've been opened/played with Terraria 1.4.1. This applies both to worlds created under 1.4.1 and pre-existing worlds opened with Terraria 1.4.1, even if only briefly.

**Comment by fartboygh** [comment]
Confirmed. Please update for the new small patch.

**Comment by mrkite** [comment]
Give me a few days, I haven't even had time to download the update yet.

**Comment by mojotx** [comment]
Bumping the following value from 230 to 233 will let the game load, but it seems that some of the default file locations have changed, at least on macOS. I just submitted PR #112 for what I did to fix my local install. 

```diff
diff --git a/world.h b/world.h
index 73aa5fa..cffb04d 100644
--- a/world.h
+++ b/world.h
@@ -35,7 +35,7 @@ class Tile {

 class World : public QObject, public QRunnable {
   static const int MinimumVersion = 88;
-  static const int HighestVersion = 230;
+  static const int HighestVersion = 233;


   Q_OBJECT
```

**Comment by JustANormalPersen** [comment]
when you are going to update to Accept 1.4.1.1 world files

**Comment by mrkite** [comment]
Updated and added new items.  I'll release linux and mac binaries in a couple of days.
