### ISSUE TITLE
No Mac version for 3.1.2

### ISSUE THREAD

**Issue by jwpjr-dev** [mrkite/TerraFirma#113]
Only Windows downloads are available for TerraFirma version 3.1.2 at the moment.

**Comment by mrkite** [comment]
Yeah, I'm having problems compiling on Big Sur.  I'll try again on monday.

**Comment by jwpjr-dev** [comment]
Sounds pretty legit, I'm trying to find an enchanted sword shrine lol

**Comment by mrkite** [comment]
Mac and Linux binaries have been uploaded.

**Comment by jwpjr-dev** [comment]
Thank you very much, kind sir!
