### ISSUE TITLE
Terraria 1.4.2 - Unsupported map version

### ISSUE THREAD

**Issue by Faiakes** [mrkite/TerraFirma#116]
I can not load 1.4.2 maps.
error 235

**Comment by kostiya** [comment]
Same

**Comment by PhilliusAstonix** [comment]
Unsupported Map Version 236 for me

**Comment by mrkite** [comment]
Yeah, they changed the world format again today.  I'll have a fix this weekend.

**Comment by Faiakes** [comment]
Any luck Sean?

**Comment by mrkite** [comment]
As best as I can tell, they haven't added anything new, so I bumped the version number and put out a new release.  I'll have linux and mac binaries attached tomorrow.

**Comment by PhilliusAstonix** [comment]
The new release fixed the issue perfectly for me and I tested all my worlds successfully. Thanks very much for the work you have put into this awesome tool and for such a fast response to the bug report.

**Comment by Faiakes** [comment]
Works fine here, too.
Thanks Sean.
(I've said it before, your's is the only map reader worth using.)
