### ISSUE TITLE
HiDPI broken with Qt6 build on macOS Mojave

### ISSUE THREAD

**Issue by MrLavender** [mrkite/TerraFirma#120]
I don't want to use the new installer so went to build the app myself as I've done in the past without problems;
```
brew install qt
git clone https://github.com/mrkite/TerraFirma.git
cd TerraFirma
qmake
make
```
A picture is worth a thousand words, this is what I get when running the resultant app;
<img width="1072" alt="qt6" src="https://user-images.githubusercontent.com/2496738/114403359-a0ce2500-9b9c-11eb-9066-c9fc6f845a63.png">

It's not just the world rendering, notice that the text in the status bar is blurry compared to the text in the title bar. Selecting "Open in Low Resolution" (from right-click app -> Get Info) does fix the rendering but the status bar and all dialog text is still blurry which is annoying. It seems like hidpi (retina display) support is completely broken here.

So I decided to build it with Qt5 instead. This requires fixing one line in `Terrafirma.pro`;
```diff
-greaterThan(QT_MAJOR_VERSION, 4): QT += widgets opengl openglwidgets
+greaterThan(QT_MAJOR_VERSION, 4): QT += widgets
+greaterThan(QT_MAJOR_VERSION, 5): QT += opengl openglwidgets
```
and then
```
make distclean
brew install qt@5
export PATH="/usr/local/opt/qt@5/bin:$PATH"
qmake
make
```
And that app works perfectly, with full hidpi support, as it did before.

So something must have changed in Qt6 but I don't know Qt well enough to investigate this further. I did try some Google searches to see if it was a known issue but didn't find anything obvious beyond that they have made a lot of changes to the graphical backend in Qt6.

**Comment by mrkite** [comment]
Thanks for this.. I haven't looked much into Qt6 either but the changes you made are clean and a good idea.

**Comment by mrkite** [comment]
I released a new binary today that doesn't seem to have this problem.
