### ISSUE TITLE
Can't build on Xubuntu 18.04

### ISSUE THREAD

**Issue by nskmda** [mrkite/TerraFirma#128]
Which version of Qt should I use to build the latest version from source?

Both Qt4 and Qt5 fail to build the project (after generating the Makefile).

Both seem to fail on the **`l10n.cpp`** but with different compilation issues.

Qt6 seems to be a commercial product now, haven't tried it yet.
Qt5 can't find a method/constructor of QList (sorry, I'm not proficient w/C++. Compilation issie is in the `getLanguages` method).
Qt4 also fails w/some unknown method or something (I can provide more details if you need).

So, anyway, hopefully a quick question. Which Qt version should I install to build the latest 3.1.6 (1.4.2.3-compatible) release source code?

**Comment by LazyDope** [comment]
The likely issue seems that you may be using an out of date version of Qt5, as I found this was the issue to be for me. The `getLanguages` method uses a function that wasn't added until Qt 5.14, however many repositories may still be using older versions, like I found that mine was still using 5.12.4.

**Comment by mrkite** [comment]
I've fixed that function to work with 5.12.  I need to make changes for the new terraria though and then I'll update things.

**Comment by mrkite** [comment]
changes merged.
