### ISSUE TITLE
fails on win7-x64

### ISSUE THREAD

**Issue by hadu-boired** [mrkite/TerraFirma#132]
this build is still supported?

- installer does not extract to user set location, %programfiles%\TerraFirma always
- execution has failed with

```
---------------------------
terrafirma.exe - Entry Point Not Found
---------------------------
The procedure entry point CreateDXGIFactory2 could not be located in the dynamic link library dxgi.dll. 
---------------------------
```

**Comment by mrkite** [comment]
I don't have a win7 box to test it on.

**Comment by vxiiduu** [comment]
I have made a compatibility pack which allows terrafirma to be run on Win7. I don't play terraria or have any terraria maps however so you will have to test whether it actually works for yourself. Let me know if it does or doesn't.
Just download the .zip and follow the steps in Instructions.txt
[Terrafirma_Win7Compat.zip](https://github.com/mrkite/TerraFirma/files/8013506/Terrafirma_Win7Compat.zip)

![Screenshot](https://user-images.githubusercontent.com/73044267/152751188-84611580-698a-4c63-9be1-1dce285585c3.png)

**Comment by mrkite** [comment]
People looking for win7 support will find this thread and your comment.
