### ISSUE TITLE
Terraria 1.4.3.6

### ISSUE THREAD

**Issue by Xioverze** [mrkite/TerraFirma#133]
No longer working on terraria 1.4.3.6
![image](https://user-images.githubusercontent.com/83839464/156422383-e7c562cb-b800-483b-88d2-263e0c5dfaa5.png)

**Comment by Youjin1985** [comment]
world.cpp, 53-56:

  if (version > HighestVersion) {
    emit loadError("Unsupported map version: " + QString::number(version));
    return;
  }

If map format changes were not so big in 1.4.3.2 - 1.4.3.2, then one can try to change
static const int HighestVersion = 244;
in (line 38) world.h to 248 and compile. Unfortunately I don't have necessary build enviroment to test it.

**Comment by Youjin1985** [comment]
@mrkite could you please try to make changes  mentioned abive if you have  time?

**Comment by mrkite** [comment]
New version released.. no guarantee it supports everything, I haven't had time to look if any changes were made.
