### ISSUE TITLE
api-ms-win-core-winrt-error-l1-1-1.dll is missing

### ISSUE THREAD

**Issue by Thimotty** [mrkite/TerraFirma#136]
I'm getting "api-ms-win-core-winrt-error-l1-1-1.dll is missing" when trying to start it.
Windows 8 64 bit
started getting this error in 3.1.7 and still getting it in 3.1.9

**Comment by mrkite** [comment]
you can download that dll here, and then just stuff it in the same folder as terrafirma.exe

https://www.dll-files.com/api-ms-win-core-winrt-error-l1-1-1.dll.html

**Comment by Thimotty** [comment]
Tried your solution but it throw another error: the application was unable to start correctly 0xc00007b
uninstalled all and tried 3.9.11 - no longer gives "api-ms-win-core-winrt-error-l1-1-1.dll is missing" (i deleted that file too) but instead it gives: "the procedure entry point createdxgifactory2 could not be located in the dynamic link library c:\program files\terrafirma\qt6gui.dll"

It looks like everything from 3.1.7 support only windows 10.

Is it possible to release 3.1.6 version (last one working on win 8) with lifted restrictions on map versions? Just to be able to open new maps will be extremely helpful even if we don't see the new stuff on the map but only the old stuff and the map itself?
