### ISSUE TITLE
Please could somebody update TerraFirma for the latest Steam version of Terraria?

### ISSUE THREAD

**Issue by TheRealSaiph** [mrkite/TerraFirma#137]
Hi all,
The current (3.1.9) version of TerraFirma is giving me an error when I try to open my map:

"Unsupported map version: 271"

Please could somebody fix this? Thanks very much!
Thanks Sean for creating such a useful utility. 

Regards,
Keith Ballard, Aylesbury UK

**Comment by mojotx** [comment]
I just started playing Terraria again, so I will see what I can do. It's now "Unsupported map version: 279".

The current TerraFirma version only supports up to [map version 248](https://github.com/mrkite/TerraFirma/blob/5511698e7612686fc0a4f95b4ac5516d661ddb2e/world.h#L38).

**Comment by mrkite** [comment]
Thanks for the update.  I'll try to update it this week.

--
sean

**Comment by mrkite** [comment]
Okay.. it's been updated.  Shimmer is drawn white because that's how the texture is stored.
