### ISSUE TITLE
Ver 3.1.10 Crashes when loading 1.4.4.9 map data

### ISSUE THREAD

**Issue by Packerman120203** [mrkite/TerraFirma#138]
ive reinstalled twice, not sure what else i can do, it doesnt give an error code like it did with the previous version that just said "unsupported map data" at which point i came and downloaded the new version. if i can be directed to what the log files are i can post them.

**Comment by Packerman120203** [comment]
...how, i know where its located but how do i send it to you

**Comment by Packerman120203** [comment]
[https://drive.google.com/drive/folders/13N8wiG2ifz9nLKbR33teu6oPz6b5Ezkk?usp=sharing](url)

no idea if this works

**Comment by mrkite** [comment]
Awesome.. can confirm there's a problem reading the partiers array.  Will fix it and put out a new version tonight.

**Comment by Packerman120203** [comment]
damn, youre good

**Comment by mrkite** [comment]
Fixed.. try out the new release.
