### ISSUE TITLE
Build issues on Manjaro Linux

### ISSUE THREAD

**Issue by InSimpleTermsJordan** [mrkite/TerraFirma#142]
(pinging @MrLavender because PR #134 suggests you got this to run on 'jaro)

Steps:
1. `git clone https://github.com/mrkite/TerraFirma.git`
2. `qmake -project`
3. `qmake -makefile -recursive`
4. `make` returns following messages:

```Makefile:1331: warning: overriding recipe for target 'main.o'
Makefile:1225: warning: ignoring old recipe for target 'main.o'
Makefile:1386: warning: overriding recipe for target 'lzx.o'
Makefile:1317: warning: ignoring old recipe for target 'lzx.o'
g++ -c -pipe -O2 -flto -fno-fat-lto-objects -Wall -Wextra -D_REENTRANT -fPIC -DQT_NO_DEBUG -DQT_GUI_LIB -DQT_CORE_LIB -I. -I. -I/usr/include/qt -I/usr/include/qt/QtGui -I/usr/include/qt/QtCore -I. -I/usr/lib/qt/mkspecs/linux-g++ -o globaleditor.o editor/globaleditor.cpp
editor/globaleditor.cpp:2:10: fatal error: QColorDialog: No such file or directory
    2 | #include <QColorDialog>
      |          ^~~~~~~~~~~~~~
compilation terminated.
make: *** [Makefile:1216: globaleditor.o] Error 1
```
I'm still a bit new to Manjaro and Linux as a whole so it's entirely likely I'm just doing something wrong

I made sure all the Qt stuff is up to date using `sudo pacman -S --needed libxcb xcb-proto xcb-util xcb-util-image xcb-util-wm libxi`

**Comment by mrkite** [comment]
I've recently had some problems with qmake myself, that's why I built out a cmakefiles.txt pipeline.  Try using cmake instead?

**Comment by mrkite** [comment]
awesome.  I'll have to fix those warnings sometime.
