### ISSUE TITLE
Crash on Map Load

### ISSUE THREAD

**Issue by StahnAileron** [mrkite/TerraFirma#143]
Getting a program crash on map load suddenly on two maps that were loading fine a week ago on Terrafirma 3.1.11. Both CotD (Win10) while the status bar indicates loading tiles (one @15%, the other @48%). The 15% crash is on a recently created world. The 48% is from one dating back to Terraria v1.06.1.

Updated to 3.1.12 and still have the same problem. Even tried a fresh install of Terrafirma (initially tried and in-place upgrade); no change.

I don't see any logs I can used to help figure out what the issue might be.

The only thing I can think of that I did common to both worlds was add a large amount of Illuminate Coating to BG walls. Other maps I have load fine (except for one other map), though I hadn't touched any of those in a long time.

**Comment by mrkite** [comment]
Is there anywhere you could upload the smallest world that's crashing so I could test it?

**Comment by StahnAileron** [comment]
Both worlds in a OneDrive folder. Let me know if you have any problems with access.

https://1drv.ms/f/s!Augwr6cXak-j_y5WjLUeodPn_2Gc?e=UspfBT

world2 crashes at 48%; 4theworthy at 15%.

**Comment by mrkite** [comment]
Thanks.. the latest version should work... I'll make mac and linux releases later.
