### ISSUE TITLE
Terrafirma fails to start in Win 8.1?

### ISSUE THREAD

**Issue by awmperry** [mrkite/TerraFirma#20]
I've just installed Terrafirma (downloaded three days ago), and it simply doesn't start. There are no error messages or anything; the desktop (or Explorer window) just loses focus for a few seconds, as if an application were opening, but then regains it. Terrafirma might appear in Task Manager, but has never been there long enough for me to spot it.

I've tried without compatibility settings and with compatibility modes for Win 8 and Win 7. I've also tried with and without Run As Admin.

Terrafirma is installed in the default location, and I'm running the latest version of Terraria through Steam.

Any idea what the problem could be and how I might make it go?

**Comment by Walkman100** [comment]
Have you tried unblocking it? Open the properties window, and if there is an "Unblock" button then click it, then ok.

![2015-7-29_20 25 44 361](https://cloud.githubusercontent.com/assets/5454764/8966159/0c4e69d0-3630-11e5-9ce0-83d2785f9e0d.png)

**Comment by awmperry** [comment]
Yup - the .msi installer needed unblocking, but the installed .exe itself is already cleared. .Net is fully up to date too.

**Comment by Walkman100** [comment]
The only thing I can think of is trying another account - if you don't have one, just create another one

**Comment by awmperry** [comment]
Another Steam account? Can't really justify buying a second copy of Terraria, if that's what you mean. :-(

**Comment by Walkman100** [comment]
No... Windows account. I doubt Steam has anything to do with this.

**Comment by schwiz** [comment]
I'm having this same problem using WINE on ubuntu.

**Comment by awmperry** [comment]
That's a thought. I've got a secondary user set up, so I'll give that a go, cheers.

**Comment by mrkite** [comment]
I will note that the binary version of Terrafirma hasn't been updated yet to work with 1.3.. so you may want to wait until I finish updating it.

**Comment by awmperry** [comment]
Ah, right - I'll give it a wait, then. All my worlds are post-1.3. When shall I check back?
