### ISSUE TITLE
Cloud save folder

### ISSUE THREAD

**Issue by flying-sheep** [mrkite/TerraFirma#22]
Hi, amazing work with that update!

I helped to update [Berserker66/omnitool](https://github.com/Berserker66/omnitool) and we found that on linux, terraria uses

1. `~/.local/share/Terraria/Worlds`
2. `~/.steam/steam/userdata/*/105600/remote/worlds` (that’s one folder per steam user on that machine)

Should be similar on windows and OSX!

**Comment by mrkite** [comment]
Awesome.. I was wondering about that.  I'll need to come up with a way to mix them in with the other worlds.

**Comment by flying-sheep** [comment]
thanks!

and yeah, it should:

* [this link](http://forums.terraria.org/index.php?threads/terraria-1-3-0-8-can-mac-linux-come-out-play.30287/) (header “Where are my world and players saved?”) says terraria saves are in `~/Library/Application Support/Terraria`
* [this one](http://doc.qt.io/qt-5/qstandardpaths.html#StandardLocation-enum) (scroll down one or two screens for the second table) says `GenericDataLocation` was `~/Library/Application Support` on OSX

the only thing i don’t know is if steam also is in `~/Library/Application Support`.
