### ISSUE TITLE
bad performance

### ISSUE THREAD

**Issue by flying-sheep** [mrkite/TerraFirma#23]
hi! it works pretty awesomely, apart from one problem: when moving the mouse over the map, the application freezes and i see the statusbar changing for quite some time (basically retracing my mouse movement) before things become responsive again.

i think there should be a way to do this asynchronously or and/or debouncing it.

PS: tag the 3.0.2 release, please :smile:

**Comment by mrkite** [comment]
Try out my most recent statusbar changes.
