### ISSUE TITLE
Dark screen

### ISSUE THREAD

**Issue by percynguyen92** [mrkite/TerraFirma#26]
It got this screen when i'm downloaded lasted version of Terrafirma
![image](https://cloud.githubusercontent.com/assets/3127083/9335746/fecce112-45ff-11e5-85ff-eb6a06c51289.png)
I can use menu bar, but notthing happen!
Terraria version: 1.3.7
Terrafirma: 3.0.5

**Comment by mrkite** [comment]
What happens if you turn off Fog of War in the menubar?

**Comment by ThexXTURBOXx** [comment]
The bug still exists for me :/ (I know, that this is old, but I only want to let you know) Even when I switch Fog of War...

**Comment by mrkite** [comment]
It was a problem with some variable names in the shaders.  It was just fixed.
