### ISSUE TITLE
Where to find Terraria's textures?

### ISSUE THREAD

**Issue by Stephenator0316** [mrkite/TerraFirma#27]
Ok, so where do I find the textures for Terraria, since the screen is greyed out and I need to find the files/folder

**Comment by mrkite** [comment]
It depends on where terraria is installed.

It defaults to c:\Program Files(x86)\Steam\steamapps\common\Terraria\Content\Images

and on Linux it's  ~/.local/share/Steam/SteamApps/common/Terraria/Content/Images
