### ISSUE TITLE
Couln't read Tiles_73

### ISSUE THREAD

**Issue by necrcocakes** [mrkite/TerraFirma#29]
I recently downloaded this software and immediately experienced a problem. When I opened my world I got this error: Couldn't read Tiles_73. I have no experience and require help, and all help is greatly appreciated. -necrocakes

**Comment by mojoTX** [comment]
@necrcocakes, what operating system are you using?

**Comment by mrkite** [comment]
People with this error usually have their texture path set incorrectly.  It should point to terraria/content/images
