### ISSUE TITLE
Texture issue with MacOS X

### ISSUE THREAD

**Issue by mojoTX** [mrkite/TerraFirma#33]
After the recent fix from @biouxtai (thanks!) I can now build TerraFirma successfully with El Capitan. There was still an issue loading the textures, however, but I was able to work around it with a hack. 

I'll be the first person to say my fix is not worthy of a pull request, but should illustrate the problem. Time permitting, I will work on a more elegant and portable solution, but my feelings won't be hurt if someone beats me to it. 

Here's a link to the commit on my fork: 

https://github.com/mojoTX/TerraFirma/commit/2ce5d01ebfc8bd235f19e2fec993062316dadf3b

Code diff:

```
$ git diff HEAD^
diff --git a/settingsdialog.cpp b/settingsdialog.cpp
index 35804f4..ea5cae0 100644
--- a/settingsdialog.cpp
+++ b/settingsdialog.cpp
@@ -46,7 +46,12 @@ SettingsDialog::SettingsDialog(QWidget *parent) : QDialog(parent),

   defaultTextures = "";
   if (terrariaDir.exists())
+#if 0
     defaultTextures = terrariaDir.absoluteFilePath("Content/Images");
+#else
+    // For MacOS
+    defaultTextures = terrariaDir.absoluteFilePath("Terraria.app/Contents/MacOS/Content/Images");
+#endif

   QDir worldDir = QDir(
         QStandardPaths::standardLocations(QStandardPaths::DocumentsLocation)
```

**Comment by mojoTX** [comment]
I think we have a solution, with thanks to @biouxtai for the assist! 

https://github.com/mojoTX/TerraFirma/commit/b4d0a4d654299d77d45ea2c08bfca6abf3ab3e2e

**Comment by mojoTX** [comment]
Pull request https://github.com/mrkite/TerraFirma/pull/34 created.

**Comment by mrkite** [comment]
PR accepted.
