### ISSUE TITLE
2 hard 2 compile :(

### ISSUE THREAD

**Issue by OUTEASTsama** [mrkite/TerraFirma#35]
/usr/lib/i386-linux-gnu/qt4/bin/uic mainwindow.ui -o ui_mainwindow.h
/usr/lib/i386-linux-gnu/qt4/bin/uic settingsdialog.ui -o ui_settingsdialog.h
/usr/lib/i386-linux-gnu/qt4/bin/uic infodialog.ui -o ui_infodialog.h
/usr/lib/i386-linux-gnu/qt4/bin/uic killdialog.ui -o ui_killdialog.h
/usr/lib/i386-linux-gnu/qt4/bin/uic chestview.ui -o ui_chestview.h
/usr/lib/i386-linux-gnu/qt4/bin/uic signview.ui -o ui_signview.h
/usr/lib/i386-linux-gnu/qt4/bin/uic findchests.ui -o ui_findchests.h
/usr/lib/i386-linux-gnu/qt4/bin/uic hilitedialog.ui -o ui_hilitedialog.h
g++ -c -pipe -std=c++11 -O2 -Wall -W -D_REENTRANT -DQT_NO_DEBUG -DQT_GUI_LIB -DQT_CORE_LIB -DQT_SHARED -I/usr/share/qt4/mkspecs/linux-g++ -I. -I/usr/include/qt4/QtCore -I/usr/include/qt4/QtGui -I/usr/include/qt4 -I. -I. -o main.o main.cpp
main.cpp:9:26: fatal error: QSurfaceFormat: No such file or directory
 #include <QSurfaceFormat>
                          ^
compilation terminated.
make: *** [main.o] Error 1

**Comment by mojoTX** [comment]
It looks like you're not compiling with Qt 5. Did you read the README.md file? If you want assistance, you should provide more information.

**Comment by OUTEASTsama** [comment]
Okay. I have Qt 5 installed. I ran qmake, then make and got Error.

g++ -c -pipe -std=c++11 -O2 -Wall -W -D_REENTRANT -fPIE -DQT_NO_DEBUG -DQT_WIDGETS_LIB -DQT_GUI_LIB -DQT_CORE_LIB -I/usr/lib/i386-linux-gnu/qt5/mkspecs/linux-g++ -I. -I/usr/include/qt5 -I/usr/include/qt5/QtWidgets -I/usr/include/qt5/QtGui -I/usr/include/qt5/QtCore -I. -I. -o main.o main.cpp
main.cpp: In function ‘int main(int, char**)’:
main.cpp:13:27: error: ‘defaultFormat’ is not a member of ‘QSurfaceFormat’
   QSurfaceFormat format = QSurfaceFormat::defaultFormat();
                           ^
main.cpp:17:3: error: ‘setDefaultFormat’ is not a member of ‘QSurfaceFormat’
   QSurfaceFormat::setDefaultFormat(format);
   ^
make: *** [main.o] Error 1

**Comment by OUTEASTsama** [comment]
Also, what qt libs are necessary to run this?

**Comment by mrkite** [comment]
Looks like defaultFormat was added in Qt 5.4.. so you'll need 5.4 or newer.

It uses QtWidgets and QOpenGL.

**Comment by mojoTX** [comment]
Yes, you need Qt 5.5. There are multiple ways to get it. I suspect the Mac OS X instructions would also work for Linux, assuming that you have all the prerequisites installed to build Qt 5.5. 

Here are OS-specific instructions for building Qt from Git:
[Building Qt 5 from Git](https://wiki.qt.io/Building_Qt_5_from_Git)
