### ISSUE TITLE
Cross-platform end-of-line normalization

### ISSUE THREAD

**Issue by mojoTX** [mrkite/TerraFirma#38]
I use TerraFirma on my Mac and Linux desktops, and I'm not a Windows guy at all. I noticed that some files have been checked in recently with MS-DOS CRLF line endings. I could just convert them to LF format, but that makes merging upstream changes tedious. 

Thankfully Git makes it easy to auto-convert, depending on your platform, although it does require creating a [.gitattributes](https://git-scm.com/docs/gitattributes) file and/or setting the `core.autocrlf` attribute to `true` if you're a Windows person, or `input` if you're a Mac/UNIX person. 

Example: 
```
# Mac or UNIX
git config --global core.autocrlf input

# Windows
git config --global core.autocrlf true
```
The [.gitattributes](https://git-scm.com/docs/gitattributes) file can be used for people who have not explicitly set the `core.autocrlf` attribute in their Git config. 

I'm about to submit a pull request that will hopefully address this issue. This [StackOverflow question](http://stackoverflow.com/questions/1510798/trying-to-fix-line-endings-with-git-filter-branch-but-having-no-luck/1511273#1511273) was very useful in figuring this out.

**Comment by mojoTX** [comment]
Pull request submitted.  🙂

https://github.com/mrkite/TerraFirma/pull/39

**Comment by mrkite** [comment]
Thanks.
