### ISSUE TITLE
map switch not handled correctly

### ISSUE THREAD

**Issue by galtgendo** [mrkite/TerraFirma#42]
Again 3.0.9.
Switching the maps doesn't seem to reset chest search data - search dialog contains data from the first map the dialog was opened on.

**Comment by galtgendo** [comment]
...it looks like adding following block at the end of MainWindow::openWorld() in mainwindow.cpp makes things work: 
```c++
if (findChests != NULL) {
  delete findChests;
  findChests = NULL;
 } 
```
...though this doesn't strike me as a fully correct solution.

**Comment by mrkite** [comment]
Oh, good catch.  I'll fix that.

**Comment by mrkite** [comment]
Fixed in newest version.

**Comment by galtgendo** [comment]
...GitHub notwithstanding, please upload/update source links on your main page too - it seems you've missed those

**Comment by mrkite** [comment]
I updated them.. but now I've got to update them again :)
