### ISSUE TITLE
Duplicated chests in "Chests" category

### ISSUE THREAD

**Issue by rahlzel** [mrkite/TerraFirma#50]
![chests](http://i.imgur.com/wfb7f63.png)

Also, somewhat related - I thought none of the dungeon chests were working because selecting "Crimson Chest" wasn't showing anything. Then I scrolled down and found "Locked Crimson Chest". Perhaps those should be combined.

Unrelated - it'd be nice to be able to search for "Crimson" and see "Crimson Chest", as an example, instead of needing to first expand the Chest category. There's a lot of items inside categories that can't be searched for because of this limitation.

**Comment by mrkite** [comment]
Yeah, the search definitely needs to apply to the sub items.  I'll also look at removing duplicates.

**Comment by mrkite** [comment]
This has changed due to the localization changes.
