### ISSUE TITLE
Update Prebuilt Ubuntu x64 Package

### ISSUE THREAD

**Issue by greysondn** [mrkite/TerraFirma#55]
Please? It's a few minor versions behind - enough to not support the current map format. ^_^

**Comment by mrkite** [comment]
Okay.  It's been updated.  I've also moved the binaries over to github's releases page, which makes it easier for people to keep track of.

**Comment by greysondn** [comment]
Thank you very much <3 I'll test it when I reboot into Ubuntu, but I'm sure it's fine, no news from me is good news on that front. Dealing with [another project](http://www.kongregate.com/forums/4/topics/663282?page=1) right now.
