### ISSUE TITLE
So ... How to export PNGs?

### ISSUE THREAD

**Issue by greysondn** [mrkite/TerraFirma#56]
On Ubuntu. I know you're learning to love me.

New package worked fine to install and load, fog of war included.

**Comment by mrkite** [comment]
You can't export PNGs anymore.  The feature has been disabled because of issues with Qt playing nice with OpenGL.  I should try it again now that Qt has updated a few times... but previously, any attempts to read from an OpenGL surface resulted in a black image.

**Comment by greysondn** [comment]
Wouldn't hurt as it was the sole reason to use TerraFirma over alternatives for me - the ability to output full-resolution PNGs with my fog of war applied to them. Was kinda stoked, was going to do an "evolution of the map" thing with

**Comment by greysondn** [comment]
Pfft, fumble fingers. 

... with that. I was going to do an "evolution of the map" thing with that.

**Comment by IGBC** [comment]
I opened the source in QtCreator and patched the button back in, wired it to `MainWindow::save()`:

![World_Map](https://user-images.githubusercontent.com/8123843/75704278-f903d980-5cb0-11ea-92f2-d80eaee13e91.png)

Yea it works with Whatever version of Qt is shipping on archlinux now.

**Comment by mrkite** [comment]
Excellent news.  I'll test it out on an integrated GPU just to be sure and then add that feature back in.

**Comment by IGBC** [comment]
Cool!

Its a shame the feature doesn't quite do what I want. I am currently picking apart the code to see how I would render the _whole_ map, not just the current view. (preferably with or without textures)

**Comment by mrkite** [comment]
This is not back in yet due to changes in the way I compile Qt needing more testing.
