### ISSUE TITLE
Underwater altars not highlighted

### ISSUE THREAD

**Issue by zauberparacelsus** [mrkite/TerraFirma#57]
When setting Terrafirma to highlight demon altars or crimson altars, it will not highlight them if they are underwater (or, presumably, submerged in other liquids).  IIRC, MoreTerra had this same problem as well.

**Comment by zauberparacelsus** [comment]
This issue also affects chests, and presumably any furniture item that can be submerged.

**Comment by robbix1206** [comment]
Same as #36

**Comment by mrkite** [comment]
Highlighting needs a rework to fix this.
