### ISSUE TITLE
not working

### ISSUE THREAD

**Issue by Mark4666** [mrkite/TerraFirma#69]
When I open any world with TerraFirma it crashes the moment it starts trying to load the npc's, I have tried reinstalling terrafirma and tried reinstalling terraria but it still doesn't work.

**Comment by mrkite** [comment]
It's probably not crashing due to the NPCs but due to something it does right afterwards, which is load textures.  Try turning off textures before you load a world and see if it still crashes.  If that fixes it, I bet you need to fix your texture path, which you can do in the settings window.

**Comment by Mark4666** [comment]
hasn't fixed it

**Comment by EastArctica** [comment]
@Mark4666 are you using a small world it seems to me they don't work with small worlds

**Comment by mrkite** [comment]
Try new version.
