### ISSUE TITLE
Update for 1.3.5?

### ISSUE THREAD

**Issue by morganbear** [mrkite/TerraFirma#73]
Unsupported map version: 193
Any chance of an update? This is by far my favorite map viewer.

**Comment by Anon411** [comment]
I echo what morgan wrote above. 

I have tried a few viewers in the past and now Terrafirma is the only stop.

**Comment by mrkite** [comment]
Been having a little bit of trouble with my static QT build.  I'll try to get a release out later today.

**Comment by morganbear** [comment]
That would be great! Thank you for your time 🥇

**Comment by mrkite** [comment]
Windows binaries built.  OSX and Linux coming in a day or so.
