### ISSUE TITLE
Blackscreen issue

### ISSUE THREAD

**Issue by Reidkon26** [mrkite/TerraFirma#78]
When i open terrafirma, it is just a blackscreen with nothing in. Pls help

**Comment by robbix1206** [comment]
:/ That's not information to try to reproduce can you at least precise :
-Which OS are you using
-Which version of OS are you using

**Comment by mrdevinh** [comment]
I appear to be having the same problem as Reidkon26 it is just a black window(I'll attach a picture). I just found out though that it may be an issue with how it's displayed as the open world settings and all the stuff in the top left still work but nothing shows up. I'm using windows 8.1 pro what would be another Qt application to test? 
![terra](https://user-images.githubusercontent.com/28285874/30623953-5e090aaa-9d80-11e7-89f4-0cfee225d3de.png)

**Comment by lmaguina** [comment]
I have the same problem and I'm using Win7. Is there a library I should install?

**Comment by williammorrow2001** [comment]
Im having the same issue if someone could please help me.

**Comment by AmberDinosaur** [comment]
I had the same issue but turning off Fog of War fixed it for me, try that.

**Comment by mrkite** [comment]
Try newest version.   This is an ANGLE problem. I compiled it differently this time.
