### ISSUE TITLE
Not working?

### ISSUE THREAD

**Issue by TheNicklao** [mrkite/TerraFirma#80]
So when I try to launch TerraFirma it shows up for a split second in the activity handler and then it dissapears. I have used both the .exe and the .msi, nothing works. I have already tried running in admin mode and with compatability settings, nothing happens. Any Ideas?

**Comment by Robopwner** [comment]
I am having the same issue with the msi installer. I have tried running as Admin as well. App does not launch. Win 10x64 v1809

**Comment by mojoTX** [comment]
Unfortunately, I can only assist with Mac and Linux.

**Comment by mrkite** [comment]
Try newest version.
