### ISSUE TITLE
no terrafirma.exe

### ISSUE THREAD

**Issue by Wavemender** [mrkite/TerraFirma#81]
I've been trying to use the install program, but after noticing I needed Wix Toolset v10 and after installing that I still get an error for no terrafirma.exe file
![screenshot 2017-11-21 08 51 19](https://user-images.githubusercontent.com/33869003/33075971-42c26ad0-ce99-11e7-8b6f-1ea5689493dd.png)

even after reinstalling TerraFirma-master still no terrafirma.exe application anywhere.

**Comment by mrkite** [comment]
You need to copy the exe from your build folder into the source folder by hand.
