### ISSUE TITLE
Load textures from mods

### ISSUE THREAD

**Issue by aidyn89** [mrkite/TerraFirma#83]
I have just downloaded Tremors, and TerraFirma doesn't seem to load the biomes added by it, just leaving a huge empty circle were the biome would have been. In this particular case, it's the glacier minibiome (in case it's relevant). I am still trying to figure out how to include Tremors textures to terrafirma

**Comment by mrkite** [comment]
Now that there's official mod support, we'll see about supporting them in the future.
