### ISSUE TITLE
Terrafirma not loading on Windows 10. No error message or prompts but Event Viewer shows APPCRASH event.

### ISSUE THREAD

**Issue by maninelevator** [mrkite/TerraFirma#85]
Any idea how to solve this issue? When opening the exe nothing happens, however event viewer is showing an appcrash error (below). I'm on Windows 10 using the latest version of Terraria. I've tried compatibility mode, running as administrator, disabled Windows Defender as well as added an exception for that particular exe (no other virus/malware scanners). I've tried running it from several different paths (Terraria folder, c:\windows, desktop, etc). Tried running it in safe mode. Nothing seems to work. Is it no longer supported on Windows 10? No longer supported at all? I downloaded 3.0.19 (both zip and msi), same issue for both. Any ideas?

Fault bucket 120752192990, type 4
Event Name: APPCRASH
Response: Not available
Cab Id: 0

Problem signature:
P1: terrafirma.exe
P2: 0.0.0.0
P3: 58fff1a2
P4: terrafirma.exe
P5: 0.0.0.0
P6: 58fff1a2
P7: c0000005
P8: 000000000061c863
P9: 
P10: 

Attached files:
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER2E3E.tmp.mdmp
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER2E5F.tmp.WERInternalMetadata.xml
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER2E5D.tmp.csv
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER2E6E.tmp.txt

These files may be available here:
C:\ProgramData\Microsoft\Windows\WER\ReportArchive\AppCrash_terrafirma.exe_f3959afbab838df9136cc524466b5edc7921462_05accc45_2c0234a6

Analysis symbol: 
Rechecking for solution: 0
Report Id: 59fef059-c946-4d1a-9ad9-67cb926a4d9f
Report Status: 268435456
Hashed bucket: 44472d0e98363e74bf95778af96a0888

**Comment by mrkite** [comment]
I'm not sure what's going on here.  Windows 10 shouldn't be an issue since
TerraFirma is compiled on Windows 10.  If I had to guess, I'd say it was an
opengl driver issue.  That's what seems to cause crashes at launch and
black screens.

Could you try to update your video drivers?

**Comment by maninelevator** [comment]
Thanks. I had the latest drivers and tried downgrading to a few legacy drivers and that didn't fix it. I was actually able to resolve the issue by switching over to Win 10 Pro vs Home (both 64 bit). Can't really explain why that would matter but yeah. Thanks for your help though.

**Comment by Techno-Waffle** [comment]
Hi, I've got a similar issue (same error code). Any way to solve this without switching to Win 10 Pro?
