### ISSUE TITLE
Crash on Application Startup

### ISSUE THREAD

**Issue by VigilPrime** [mrkite/TerraFirma#86]
Anytime I attempt to run Terrafirma as a unprivileged user, the application fails. Interface doesn't appear at all, the game just application just crashes. Only way I can run the client is as an Administrator which I'd really rather avoid.

I've tried uninstalling and reinstalling with the MSI in multiple locations, running it with the standalone executable, restarting, etc etc.

Currently using most up to date version of Terrafirma and Windows 7 Ulttimate 64 bit. The Windows Crash Handler reports the following:

Problem signature:
  Problem Event Name:	APPCRASH
  Application Name:	terrafirma.exe
  Application Version:	0.0.0.0
  Application Timestamp:	58fff1a2
  Fault Module Name:	terrafirma.exe
  Fault Module Version:	0.0.0.0
  Fault Module Timestamp:	58fff1a2
  Exception Code:	c0000005
  Exception Offset:	000000000061c863
  OS Version:	6.1.7601.2.1.0.256.1
  Locale ID:	1033
  Additional Information 1:	d927
  Additional Information 2:	d927b02db93a182b677248c88a8b3cb5
  Additional Information 3:	21c4
  Additional Information 4:	21c4aa12a08c8a04fe3895bb6178ec36

Any help would be greatly appreciated.

**Comment by MrDj200** [comment]
Same problem here. But  it does not even start with admin rights

**Comment by EmberAnimus** [comment]
The issue still persists. Not sure why or if it will ever be resolved.

**Comment by mrkite** [comment]
Try newest version.
