### ISSUE TITLE
Segmentation fault

### ISSUE THREAD

**Issue by liquid600pgm** [mrkite/TerraFirma#87]
When I try to launch the app, it just gives a segmentation fault.

```sh
daknus@daknus MINGW64 ~/Desktop
$ ./terrafirma.exe
Segmentation fault
```

OS: Windows 10 Spring Creators Update
Terraria: 1.3.5.4
TerraFirma: 3.0.19

**Comment by Goury** [comment]
Ubuntu 16.04, same shit.
TerraFirma: 3.0.18, 3.0.19.

**Comment by mrkite** [comment]
Try newest version.
