### ISSUE TITLE
Feature request: Highlight walls of specific type / highlight corruption / crimson of specific type

### ISSUE THREAD

**Issue by johnbeech** [mrkite/TerraFirma#90]
I want to purify large worlds of all Crimson (and Corruption), and so I use Terrafirma as a visual guide to highlight specific blocks to be converted.

I have a theory that Crimson walls may count towards the corruption/crimson count at the Dryad, and wanted to try and highlight any remaining unconverted walls.

In the editor, convertible Crimson Walls come up as Hellstone Wall (as opposed to Hellstone Brick Wall), and I would like to be able to highlight these to make them easier to find. This might also mean hiding visible blocks.

It would also be useful to highlight multiple blocks / types so that all forms of corruption could be highlighted at the same time.

For Crimson biomes I believe the list to be:
- Crimson Hardened Sand
- Crimson Sandstone
- Crimsand
- Crimstone
- Crimstone Vines
- Flesh Grass
- Flesh Weeds
- Hellstone Wall

For Corruption biomes I believe the list to be:
- Corrupt Hardened Sand
- Corrupt Sandstone
- Ebonsand
- Ebonstone
- Ebonstone Vines
- Corrupted Grass
- Corrupted Weeds
- (Stone Wall) [corrupted colouring]

For Hallowed Biomes:
- Hallow Hardened Sand
- Hallow Sandstone
- Pearlstone
- Hallow Vines
- Hallow Grass
- Hallowed Weeds
- Hallowed Weeds (second type?)
- Pearlstone Wall

It would be useful to "Highlight All Forms of Corruption" as a guide to players showing how corrupt a world still is, and provide a count of remaining blocks.

Commentary welcome, I may or may not have a go at modifying Terrafirma on a branch if I can get it to build and have a go at implementing the features myself.

![image](https://user-images.githubusercontent.com/6341696/50457366-cd6dbc80-0952-11e9-9e19-13f96cf8f0b1.png) A corruption free expert post-hardmode world.

![image](https://user-images.githubusercontent.com/6341696/50457376-e8d8c780-0952-11e9-97c6-e48e1dbb001e.png) Highlighting pearlsand.

![image](https://user-images.githubusercontent.com/6341696/50457381-f68e4d00-0952-11e9-9d51-7450e8fbf965.png) Separately highlighting pearlstone.

**Comment by mrkite** [comment]
Not the worst idea, but the highlight system is getting reworked. We'll see how it goes.
